before_script:
    - curl -sSfL -o ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
    - composer install --dev --no-interaction --prefer-source

branches:
    only:
        - master

git:
    depth: 1

jobs:

    allow_failures:
        - php: nightly
        - php: hhvm-nightly

    fast_finish: true

    include:
        - php: 7.0
        - php: nightly
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge

language: php

script: phpunit --testdox
